function zap();
% -------------------------------------------------------------------------
% Zero-mode waveguide (ZMW) Analysis Platform (ZAP)
% -------------------------------------------------------------------------
% Author: David S. White
% Contact: dswhite2012@gmail.com
% License: GPLv3.0

% updates: 
% 2019-12-10 DSW wrote the figure

% To Do:
% should normalize the position - done. DSW 2019-12-12

% -------------------------------------------------------------------------
% launch the ZAP app
zapApp = figure('Name', 'ZAP', 'NumberTitle','off','MenuBar','None',...
    'units','normalized', 'Position',[0.4,0.3,0.20,0.45],'Resize','off');

% Welcome Text
welcomeText1 = uicontrol(zapApp,...
    'Style','text',...
    'units','normalized',...
    'Position',[0.1 0.75 0.8 0.2],...
    'String','Welcome to Z.A.P.!',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',18);
welcomeText2 = uicontrol(zapApp,...
    'Style','text',...
    'units','normalized',...
    'Position',[0.1 0.69 0.8 0.2],...
    'String','ZMW Analysis Platform',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',12);

% Routines:
% 1. mask Maker
button_maskMaker = uicontrol(zapApp,...
    'Style','pushbutton',...
    'units','normalized',...
    'Position',[0.1 0.7 0.8 0.12],...
    'String','Mask Maker',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',12,...
    'Callback', @launch_maskMaker);

% 2. Image Projection
button_roiProjection = uicontrol(zapApp,...
    'Style','pushbutton',...
    'units', 'normalized',...
    'Position', [0.1 0.58 0.8 .12],...
    'String','Image Processing',...
    'HorizontalAlignment','left',...
    'FontName','Helvetica',...
    'FontSize',12,...
    'Callback', @launch_roiProjection);

% 3. Trajectory Navigation and DISC
button_roiViewer = uicontrol(zapApp,...
    'Style','pushbutton',...
    'units', 'normalized',...
    'Position',[0.1 0.46 0.8 .12],...
    'String','Trajectory Viewer & DISC',...
    'HorizontalAlignment','left',...
    'FontName','Helvetica',...
    'FontSize',12,...
    'Callback', @launch_roiViewer);

% 4. Analysis
button_analysis = uicontrol(zapApp,...
    'Style','pushbutton',...
    'units', 'normalized',...
    'Position', [0.1 0.34 0.8 0.12],...
    'String','Analysis',...
    'HorizontalAlignment','left',...
    'FontName','Helvetica','FontSize',12,...
    'Callback', @launch_analysis);

% Closing Text
closingText1 = uicontrol(zapApp,...
    'Style','text',...
    'units', 'normalized',...
    'Position',[0.1 0.1 0.8 0.1],...
    'String','version 0.0.1',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',10);
closingText2 = uicontrol(zapApp,...
    'Style','text',...
    'units', 'normalized',...
    'Position',[0.1 0.05, 0.8 0.1],...
    'String','David S. White',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',10);

% Callbacks.
    function launch_maskMaker(obj,event)
        close(findobj('Name','ZAP'));
        maskMaker;
    end

    function launch_roiProjection(obj,event)
        close(findobj('Name','ZAP'));
        projectionGUI;
    end

    function launch_roiViewer(obj,event)
        %close(findobj('Name','ZAP'));
         errordlg('Error getting DISCO to work...');
        % DISCO
    end

    function launch_analysis(obj,event)
        % close(findobj('Name','ZAP'));
        errordlg('Sorry! Analysis tab is still under development');
    end

end
